useTabs: false
tabWidth: 2
endOfLine: lf
printWidth: 160
singleQuote: true
trailingComma: all
plugins:
- "./node_modules/@typespec/prettier-plugin-typespec/dist/index.js"
overrides: [{"files": "*.tsp", "options": {"parser": "typespec"}}]
