useTabs: false
tabWidth: 2
endOfLine: lf
printWidth: 160
singleQuote: true
trailingComma: all
plugins:
  - "@typespec/prettier-plugin-typespec" 
overrides: [{"files": "*.tsp", "options": {"parser": "typespec"}}]
