openapi: 3.0.0
info:
  title: RAMSES
  version: dev
tags:
  - name: Orders
  - name: Importable Orders
  - name: Attachments
  - name: Composition Lines
  - name: Additional Purchase Lines
  - name: Order Material Items
paths:
  /order-manager/additional-purchase-lines/{id}:
    patch:
      tags:
        - Additional Purchase Lines
      operationId: AdditionalPurchaseLines_update
      parameters:
        - $ref: '#/components/parameters/AdditionalPurchaseLine.id'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdditionalPurchaseLine'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_no:
                  type: string
    delete:
      tags:
        - Additional Purchase Lines
      operationId: AdditionalPurchaseLines_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/attachments/{id}:
    get:
      tags:
        - Attachments
      operationId: OrderAttachments_read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderAttachment'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Attachments
      operationId: OrderAttachments_delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/composition-lines/{id}:
    patch:
      tags:
        - Composition Lines
      operationId: OrderCompositionLines_update
      parameters:
        - $ref: '#/components/parameters/OrderCompositionLine.id'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCompositionLine'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_no:
                  type: string
  /order-manager/importable-orders:
    get:
      tags:
        - Importable Orders
      operationId: ImportableOrders_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SyncedOrder'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/order-material-items/{id}:
    patch:
      tags:
        - Order Material Items
      operationId: OrderMaterialItems_update
      parameters:
        - $ref: '#/components/parameters/OrderMaterialItem.id'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderMaterialItem'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_no:
                  type: string
                material_no:
                  type: string
                item_no:
                  type: string
                qty_calculated:
                  type: integer
                  format: uint16
                user_qty:
                  type: integer
                  format: uint16
  /order-manager/orders:
    get:
      tags:
        - Orders
      operationId: Orders_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/orders/import:
    post:
      tags:
        - Orders
      operationId: Orders_postImport
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: string
                delivery_date:
                  type: string
                  format: date-time
                prod_duration_in_days:
                  type: integer
                  format: uint8
                  minimum: 0
                  maximum: 50
              required:
                - order_id
  /order-manager/orders/{id}:
    get:
      tags:
        - Orders
      operationId: Orders_read
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - Orders
      operationId: Orders_update
      parameters:
        - $ref: '#/components/parameters/Order.id'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                client_no:
                  type: string
                client_name:
                  type: string
                project_manager:
                  type: string
                status:
                  type: string
                ext_created_at:
                  type: string
                  format: date-time
  /order-manager/orders/{id}/additional-purchase-lines:
    get:
      tags:
        - Orders
      operationId: Orders_getAdditionalPurchLines
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdditionalPurchaseLine'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Orders
      operationId: Orders_postAdditionalPurchLines
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/orders/{id}/attachments:
    get:
      tags:
        - Orders
      operationId: Orders_getAttachments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderAttachment'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Orders
      operationId: Orders_postAttachments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/orders/{id}/composition-lines:
    get:
      tags:
        - Orders
      operationId: Orders_getCompositionLines
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderCompositionLine'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/orders/{id}/order-materials:
    get:
      tags:
        - Orders
      operationId: Orders_getOrderMaterials
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderMaterial'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /order-manager/orders/{id}/push-to-erp:
    post:
      tags:
        - Orders
      operationId: Orders_postToErp
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: string
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  parameters:
    AdditionalPurchaseLine.id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: uint64
    Order.id:
      name: id
      in: path
      required: true
      schema:
        type: string
    OrderCompositionLine.id:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: uint64
    OrderMaterialItem.id:
      name: id
      in: path
      required: true
      schema:
        type: string
  schemas:
    AdditionalPurchaseLine:
      type: object
      required:
        - id
        - order_no
      properties:
        id:
          type: integer
          format: uint64
        order_no:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Order:
      type: object
      required:
        - id
        - name
        - client_no
        - client_name
        - project_manager
        - status
        - ext_created_at
      properties:
        id:
          type: string
        name:
          type: string
        client_no:
          type: string
        client_name:
          type: string
        project_manager:
          type: string
        status:
          type: string
        ext_created_at:
          type: string
          format: date-time
    OrderAttachment:
      type: object
      required:
        - id
        - order_no
        - type
        - path
      properties:
        id:
          type: string
        order_no:
          type: string
        type:
          type: string
        path:
          type: string
    OrderCompositionLine:
      type: object
      required:
        - id
        - order_no
      properties:
        id:
          type: integer
          format: uint64
        order_no:
          type: string
    OrderMaterial:
      type: object
      required:
        - id
        - order_no
        - material_no
        - material_name
        - brutto_qty_m2
        - netto_qty_m2
        - orderMaterialItems
      properties:
        id:
          type: string
        order_no:
          type: string
        material_no:
          type: string
        material_name:
          type: string
        brutto_qty_m2:
          type: number
          format: float
        netto_qty_m2:
          type: number
          format: float
        orderMaterialItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderMaterialItem'
    OrderMaterialItem:
      type: object
      required:
        - id
        - order_no
        - material_no
        - item_no
        - qty_calculated
        - user_qty
      properties:
        id:
          type: string
        order_no:
          type: string
        material_no:
          type: string
        item_no:
          type: string
        qty_calculated:
          type: integer
          format: uint16
        user_qty:
          type: integer
          format: uint16
    SyncedOrder:
      type: object
      required:
        - id
        - name
        - client_no
        - client_name
        - project_manager
      properties:
        id:
          type: string
        name:
          type: string
        client_no:
          type: string
        client_name:
          type: string
        project_manager:
          type: string
    Versions:
      type: string
      enum:
        - v1
        - dev
